# Generated by Django 4.0.6 on 2022-08-11 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_todo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'ToDo', 'verbose_name_plural': 'ToDo'},
        ),
    ]
